renovate:
  image: renovate/renovate
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_AUTODISCOVER: 'true'
    RENOVATE_AUTODISCOVER_FILTER: "${CI_PROJECT_PATH}"
    RENOVATE_ENDPOINT: "${CI_API_V4_URL}"
    LOG_LEVEL: debug
  script: renovate
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
